config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :reports

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id]);
  end

  def new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.save
    redirect_to @report
  end

  def update
  end

  def destroy
  end

  # public methods; as mentioned earlier in this guide, they must be placed
  # before any private or protected method in the controller in order to work.
  private
  def report_params
    params.require(:report).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reporting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/index.html.erb
<h1>Hello Reports</h1>
<%= link_to('Create a new report?', new_report_path) %>

<h3>Reports</h3>
<% @reports.each do |r| %>
    <%= r.title %><br>
    <%= r.text %>
    <hr>
<% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= form_for :report, url: reports_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/reports/show.html.erb
<h1>Report Detail</h1>

<h3>Title: <%= @report.title %></h3>

<p>
  <%= @report.text %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>